version: '3.9'

services:
  web:
    image: keinermendoza/test-london:v1
    volumes:
      - ./project/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - "127.0.0.1:8000:8000"

    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - /home/env/london/.env
  
volumes:
  static_volume:
  media_volume: