version: '3.9'

services:
  web:
    image: keinermendoza/lodon-test:v1
    volumes:
      - ./project/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - "127.0.0.1:8000:8000"

    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    enviorment:
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
  
volumes:
  static_volume:
  media_volume: