# Generated by Django 5.0.6 on 2024-05-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='attachment',
            field=models.FileField(upload_to='example'),
        ),
    ]
