name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@v4
        
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose.prod.yml"
      env:
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
        SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        SQL_HOST: ${{ secrets.SQL_HOST }}
        SQL_PORT: ${{ secrets.SQL_PORT }}