name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
 
    steps:
    - uses: actions/checkout@v4
        
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose.prod.yml"
    